"""
hallucination_guard.py
======================
3-Layer Hallucination Validation Guard — Improvement 2 over the paper.

The paper acknowledges hallucinations (e.g. "MTKs" misidentified) but provides
no automated detection. In security contexts, an incorrect CVE ID or wrong
mitigation can be actively dangerous. This module adds three verification layers.

Layer 1 — CVE ID Verification:
    Regex-extract all CVE-YYYY-NNNNN patterns from LLM output.
    For each CVE ID, query the NVD API to confirm it exists.
    Flag any ID not found in NVD as "hallucinated."

Layer 2 — Semantic Consistency:
    Use BERTScore to compare the LLM answer against the retrieved RAG context.
    If F1 < bert_threshold (default 0.7), mark the answer as "LOW CONFIDENCE."
    BERTScore uses contextual BERT embeddings — it detects paraphrasing, not just
    exact word overlap.

Layer 3 — STRIDE Taxonomy Validation:
    Check every identified threat against the official STRIDE categories:
      Spoofing, Tampering, Repudiation, Information Disclosure,
      Denial of Service, Elevation of Privilege.
    Threats that don't map to any STRIDE category are flagged.

Libraries used:
  - re (stdlib)   : regex for CVE ID pattern matching
  - requests      : NVD API HTTP calls
  - bert_score    : BERTScore semantic similarity (pip install bert-score)
  - time (stdlib) : NVD rate-limit sleep
"""

import logging
import re
import time
from typing import Dict, List, Optional, Tuple

import requests  # HTTP client for NVD API

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────────
NVD_BASE_URL = "https://services.nvd.nist.gov/rest/json/cves/2.0"

# Regex pattern for CVE identifiers: CVE-YYYY-NNNNN (4–7 digit suffix)
CVE_PATTERN = re.compile(r"CVE-\d{4}-\d{4,7}", re.IGNORECASE)

# STRIDE threat categories — all valid values a threat's category must match
STRIDE_CATEGORIES = {
    "spoofing", "tampering", "repudiation",
    "information disclosure", "denial of service", "elevation of privilege",
    "s", "t", "r", "i", "d", "e",   # abbreviations also accepted
}

# BERTScore F1 threshold: below this → LOW CONFIDENCE
DEFAULT_BERT_THRESHOLD = 0.7


class HallucinationGuard:
    """
    Validates LLM output across three layers to detect factual errors.

    Usage:
        guard = HallucinationGuard()
        report = guard.validate_output(llm_answer, retrieved_context, threats=[...])
        if report["hallucination_detected"]:
            print("Hallucinated CVEs:", report["hallucinated_cves"])
    """

    def __init__(
        self,
        nvd_api_key:    Optional[str] = None,
        bert_threshold: float         = DEFAULT_BERT_THRESHOLD,
    ) -> None:
        """
        Args:
            nvd_api_key    : NVD API key for higher rate limits (reads NVD_API_KEY env var if None)
            bert_threshold : minimum BERTScore F1 to consider an answer HIGH CONFIDENCE
        """
        import os
        self.nvd_api_key    = nvd_api_key or os.getenv("NVD_API_KEY")
        self.bert_threshold = bert_threshold

        # In-process cache: avoid querying NVD for the same CVE ID twice
        self._cve_cache: Dict[str, bool] = {}

    # ══════════════════════════════════════════════════════════════════════════
    # LAYER 1 — CVE ID Verification
    # ══════════════════════════════════════════════════════════════════════════

    def verify_cve_ids(self, llm_output: str) -> Tuple[List[str], List[str]]:
        """
        Extract all CVE IDs from LLM output and verify each against NVD.

        Args:
            llm_output : the raw text generated by the LLM

        Returns:
            Tuple of:
              verified_cves     : CVE IDs confirmed to exist in NVD
              hallucinated_cves : CVE IDs NOT found in NVD (fabricated by LLM)
        """
        # Regex extracts all CVE-YYYY-NNNNN patterns, case-insensitively
        found = list(set(CVE_PATTERN.findall(llm_output)))  # deduplicate
        if not found:
            return [], []   # no CVE IDs mentioned → nothing to verify

        verified, hallucinated = [], []

        for cve_id in found:
            cve_upper = cve_id.upper()  # normalise to uppercase

            # Use cache to avoid re-querying the same CVE ID
            if cve_upper in self._cve_cache:
                (verified if self._cve_cache[cve_upper] else hallucinated).append(cve_upper)
                continue

            # Query NVD API
            exists = self._check_cve_in_nvd(cve_upper)
            self._cve_cache[cve_upper] = exists   # cache the result
            (verified if exists else hallucinated).append(cve_upper)

            # Respect NVD rate limit
            sleep_sec = 0.6 if self.nvd_api_key else 6.0
            time.sleep(sleep_sec)

        if hallucinated:
            logger.warning("⚠ HALLUCINATED CVEs detected: %s", hallucinated)

        return verified, hallucinated

    def _check_cve_in_nvd(self, cve_id: str) -> bool:
        """
        Query NVD for a specific CVE ID and return True if it exists.

        Args:
            cve_id : uppercase CVE identifier (e.g. "CVE-2021-44228")

        Returns:
            True if the CVE exists in NVD; True also if the API is unreachable
            (safe default — we don't flag as hallucinated on API failure).
        """
        headers = {"apiKey": self.nvd_api_key} if self.nvd_api_key else {}
        try:
            resp = requests.get(
                NVD_BASE_URL,
                params={"cveId": cve_id},
                headers=headers,
                timeout=15,
            )
            data = resp.json()
            return data.get("totalResults", 0) > 0   # 0 results → CVE not found
        except Exception as exc:
            logger.warning("NVD check failed for %s: %s — assuming valid", cve_id, exc)
            return True   # fail-open: assume valid when API is unreachable

    # ══════════════════════════════════════════════════════════════════════════
    # LAYER 2 — Semantic Consistency (BERTScore)
    # ══════════════════════════════════════════════════════════════════════════

    def check_semantic_consistency(
        self,
        llm_output: str,
        retrieved_context: str,
    ) -> Dict:
        """
        Measure semantic alignment between the LLM answer and RAG context using BERTScore.

        BERTScore computes token-level cosine similarity using contextual BERT embeddings.
        Unlike BLEU (n-gram overlap), BERTScore captures meaning equivalence — it
        correctly scores paraphrases highly.

        Args:
            llm_output        : the generated answer from the LLM
            retrieved_context : the concatenated chunks retrieved from the vector DB

        Returns:
            Dict with keys:
              bert_f1       : float 0–1 (F1 semantic similarity score)
              confidence    : "HIGH" (≥ threshold) or "LOW" (< threshold)
              needs_review  : True if confidence is LOW
        """
        try:
            from bert_score import score as bert_score_fn  # pip install bert-score

            # bert_score returns tensors for Precision, Recall, F1
            # rescale_with_baseline shifts scores to be more interpretable
            P, R, F1 = bert_score_fn(
                [llm_output],
                [retrieved_context],
                lang="en",
                rescale_with_baseline=True,
            )
            f1_value = float(F1[0])

            return {
                "bert_f1":      round(f1_value, 4),
                "confidence":   "HIGH" if f1_value >= self.bert_threshold else "LOW",
                "needs_review": f1_value < self.bert_threshold,
            }

        except ImportError:
            logger.warning(
                "bert-score not installed — skipping semantic check. "
                "Install with: pip install bert-score"
            )
            return {"bert_f1": None, "confidence": "UNKNOWN", "needs_review": False}

    # ══════════════════════════════════════════════════════════════════════════
    # LAYER 3 — STRIDE Taxonomy Validation
    # ══════════════════════════════════════════════════════════════════════════

    def validate_stride_mapping(self, threats: List[Dict]) -> List[Dict]:
        """
        Ensure each identified threat maps to a valid STRIDE category.

        STRIDE = Spoofing, Tampering, Repudiation, Information Disclosure,
                 Denial of Service, Elevation of Privilege
                 (Microsoft threat modelling framework)

        Args:
            threats : list of threat dicts, each with a "stride_category" key

        Returns:
            Same list with a "stride_valid" boolean added to each dict
        """
        validated = []
        for threat in threats:
            category   = threat.get("stride_category", "").lower()
            # Check if any official STRIDE token appears in the category string
            is_valid   = any(s in category for s in STRIDE_CATEGORIES)
            threat_out = dict(threat)     # copy to avoid mutating caller's data
            threat_out["stride_valid"] = is_valid

            if not is_valid:
                logger.warning(
                    "⚠ Threat '%s' has unrecognised STRIDE category: '%s'",
                    threat.get("threat_name", "?"), category,
                )
            validated.append(threat_out)
        return validated

    # ══════════════════════════════════════════════════════════════════════════
    # COMBINED REPORT
    # ══════════════════════════════════════════════════════════════════════════

    def validate_output(
        self,
        llm_output: str,
        context:    str,
        threats:    Optional[List[Dict]] = None,
    ) -> Dict:
        """
        Run all three validation layers and return a combined confidence report.

        Args:
            llm_output : generated LLM answer text
            context    : RAG-retrieved context (concatenated chunks)
            threats    : optional list of structured threat dicts for Layer 3

        Returns:
            Dict with keys:
              verified_cves       : confirmed CVE IDs
              hallucinated_cves   : fabricated CVE IDs
              hallucination_detected : bool
              semantic_consistency : Layer 2 dict
              stride_validation   : Layer 3 list
              overall_confidence  : "HIGH" | "MEDIUM" | "LOW"
        """
        # Layer 1
        verified, hallucinated = self.verify_cve_ids(llm_output)

        # Layer 2
        semantic = self.check_semantic_consistency(llm_output, context)

        # Layer 3
        stride_results = self.validate_stride_mapping(threats or [])

        # Derive overall confidence
        if not hallucinated and semantic.get("confidence") == "HIGH":
            overall = "HIGH"
        elif not hallucinated:
            overall = "MEDIUM"
        else:
            overall = "LOW"

        return {
            "verified_cves":        verified,
            "hallucinated_cves":    hallucinated,
            "hallucination_detected": bool(hallucinated),
            "semantic_consistency": semantic,
            "stride_validation":    stride_results,
            "overall_confidence":   overall,
        }
